import Foundation

final class OpenCodeProvider: Provider {
    let name = "opencode"
    let supportsVoiceHooks = false

    func setup(workDir: String, hooksPort: Int, agentID: String, taskID: String) throws {
        let pluginDir = "\(workDir)/.opencode/plugins"
        try FileManager.default.createDirectory(atPath: pluginDir, withIntermediateDirectories: true)
        let plugin = buildPlugin(hooksPort: hooksPort, agentID: agentID, taskID: taskID)
        try plugin.write(toFile: "\(pluginDir)/tasksquad.ts", atomically: true, encoding: .utf8)
    }

    func setupVoice(workDir: String, hooksPort: Int) throws {
        throw ProviderError.notSupported("voice hooks")
    }

    func extraArgs() -> [String] { ["--print-logs"] }

    private func buildPlugin(hooksPort: Int, agentID: String, taskID: String) -> String {
        """
        // Auto-generated by VTMD — do not edit
        export const TaskSquadPlugin = async ({ client }) => {
          await client.app.log({ body: { service: "vtmd", level: "info", message: "Plugin initialized" } })
          const post = async (path, body) => {
            try {
              await fetch("http://localhost:\(hooksPort)" + path, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(body)
              })
            } catch (e) {
              await client.app.log({ body: { service: "vtmd", level: "error", message: "hook error: " + e.message } })
            }
          }
          const messageCache = new Map()
          let pendingToolCount = 0
          let sessionIdleSent = false
          return {
            "event": async (input) => {
              const { event } = input
              if (event.type === "message.part.updated" && event.properties?.part) {
                const part = event.properties.part
                if (part.type === "text" && part.messageID) {
                  if (!messageCache.has(part.messageID)) messageCache.set(part.messageID, { textParts: [], completed: false })
                  const cached = messageCache.get(part.messageID)
                  const existing = cached.textParts.find(p => p.id === part.id)
                  if (existing) { existing.text = part.text || "" } else { cached.textParts.push({ id: part.id, text: part.text || "" }) }
                }
              }
              if (event.type === "message.updated" && event.properties?.info) {
                const info = event.properties.info
                if (info.role === "assistant" && info.time?.completed && messageCache.has(info.id)) messageCache.get(info.id).completed = true
              }
              if (event.type === "tool.execute.before") pendingToolCount++
              if (event.type === "tool.execute.after") {
                pendingToolCount = Math.max(0, pendingToolCount - 1)
                if (pendingToolCount === 0 && !sessionIdleSent) {
                  let lastCompleted = null
                  for (const [, cached] of messageCache.entries()) { if (cached.completed) lastCompleted = cached }
                  const message = lastCompleted ? lastCompleted.textParts.map(p => p.text).join("") : ""
                  await post("/hooks/stop?agent=\(agentID)&task_id=\(taskID)&provider=opencode", { stop_reason: "idle", message })
                  sessionIdleSent = true
                }
              }
              if (event.type === "session.idle" && pendingToolCount === 0 && !sessionIdleSent) {
                let lastCompleted = null
                for (const [, cached] of messageCache.entries()) { if (cached.completed) lastCompleted = cached }
                const message = lastCompleted ? lastCompleted.textParts.map(p => p.text).join("") : ""
                await post("/hooks/stop?agent=\(agentID)&task_id=\(taskID)&provider=opencode", { stop_reason: "idle", message })
                sessionIdleSent = true
              }
              if (event.type === "session.error") {
                const errMsg = event.properties?.error?.message || "Unknown error"
                await post("/hooks/stop?agent=\(agentID)&task_id=\(taskID)&provider=opencode", { stop_reason: "error", message: errMsg })
              }
              if (event.type === "session.updated" && event.properties?.info?.role === "user") { sessionIdleSent = false; messageCache.clear(); pendingToolCount = 0 }
            },
          }
        }
        """
    }
}
